# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_auto_20161010_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
