# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20170205_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='specs',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
