# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20170205_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='house_type',
            field=models.IntegerField(choices=[(1, 'House'), (2, 'ApartmentBuilding')], default=1),
        ),
    ]
