# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_expire', models.DateField(default=datetime.datetime(2017, 2, 25, 14, 2, 44, 676250, tzinfo=utc))),
                ('invitee_email', models.EmailField(max_length=256)),
                ('authorization', models.PositiveSmallIntegerField(default=2)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
