# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='authorization',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guest'), (2, 'Participant'), (3, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='date_expire',
            field=models.DateField(default=datetime.datetime(2017, 2, 26, 11, 32, 46, 22415, tzinfo=utc)),
        ),
    ]
