# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170219_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='date_expire',
            field=models.DateField(default=datetime.datetime(2017, 2, 26, 11, 49, 4, 486616, tzinfo=utc)),
        ),
    ]
